### ISSUE TITLE
Incorrect highlight nested snippets placeholder

### ISSUE THREAD

**Issue by bokunodev** [jeff-hykin/better-snippet-syntax#1]
Example
```json
	"Check if err is not nil": {
		"prefix": "ife",
		"body": [
			"if err != nil {",
			"\t${1:panic(${2:err})}",
			"}",
			"$0",
		],
		"description": "Check if err is not nil"
	},
```
Reference
https://code.visualstudio.com/docs/editor/userdefinedsnippets#_placeholders
Screenshot
![image](https://user-images.githubusercontent.com/54968427/208315269-8c8e96a0-0562-4c8f-8371-6e26e8270079.png)

**Comment by jeff-hykin** [comment]
should now be fixed with `v0.0.2`

**Comment by RedCMD** [comment]
Extension on marketplace hasn't been updated to `v0.0.2` yet

**Comment by jeff-hykin** [comment]
can't believe I missed that, thanks for telling me. Should be available now
